version: "2"
services:
  database:
    image: mysql
    container_name: koin-mysql
    ports: 
      - 3306:3306
    networks:
      - default
    environment:
      MYSQL_DATABASE: financial-db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
        - ./db-data:/var/lib/mysql
  solr:
    image: solr
    container_name: koin-solr
    ports:
      - 8983:8983
    environment:
      ambiente: 
    networks:
      - default